HOCS-5251: Remove actionDataUuid from Docs service
UKHomeOffice/hocs-docs pull request #259
Opened 2022-06-22 11:10 UTC by sameerinfo2003

JIRA Link : https://collaboration.homeoffice.gov.uk/jira/browse/HOCS-5251

<img width="1440" alt="Screenshot 2022-06-22 at 12 05 50" src="https://user-images.githubusercontent.com/6865972/175015153-d27d694d-7c4c-43e7-9182-c58e50173328.png">

2022-06-22 11:13 UTC, LiamMacP requested changes
This needs the table column removing as well - aslong as removing from the `DocumentData` entity.

2022-06-22 13:19 UTC, nickmcmahon01 commented
> This needs the table column removing as well - along with removing the property from the `DocumentData` entity.

This could be done in a separate PR, release 1 to remove from the DTO, release 2 to remove from the table?

2022-06-22 13:20 UTC, LiamMacP commented
Yep agreed for the table but should still be part of the ticket. Removing from the entity in this case does need to be done here. That way we can avoid breaking changes on release.

2022-06-23 08:32 UTC, nickmcmahon01 commented
can we coordinate merging this in too: https://github.com/UKHomeOffice/hocs-docs/pull/254  to avoid a double major version increment.

2022-06-24 10:20 UTC, LiamMacP commented on src/main/java/uk/gov/digital/ho/hocs/document/dto/CreateDocumentRequest.java
> -@AllArgsConstructor
Could have got rid of the existing constructor and kept this - I'm not overly fussed though.

2022-06-24 10:32 UTC, LiamMacP approved these changes

2022-06-24 10:37 UTC, merged